#!/usr/bin/env python3
"""
Phase summary generator for the MQTT comparison project.

This script helps document the completion of each phase by creating
a timestamped summary file in docs/_summaries/.
"""

import os
import sys
from datetime import datetime
from pathlib import Path


def main():
    if len(sys.argv) < 3:
        print("Usage: summarize_phase.py <phase_name> <summary_text>")
        print("\nExample:")
        print('  summarize_phase.py bootstrap "Core infrastructure completed"')
        sys.exit(1)

    phase_name = sys.argv[1]
    summary_text = sys.argv[2]

    # Get the project root directory
    script_dir = Path(__file__).resolve().parent
    summaries_dir = script_dir / "docs" / "_summaries"
    summaries_dir.mkdir(parents=True, exist_ok=True)

    # Create timestamped summary file
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{timestamp}_{phase_name}.md"
    filepath = summaries_dir / filename

    content = f"""# Phase: {phase_name}

**Date**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Summary

{summary_text}

---
Generated by summarize_phase.py
"""

    with open(filepath, "w") as f:
        f.write(content)

    print(f"✓ Phase summary written to: {filepath}")


if __name__ == "__main__":
    main()
