/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor_data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sensor_data.pb-c.h"
void   mqtt_comparison__sensor_data__init
                     (MqttComparison__SensorData         *message)
{
  static const MqttComparison__SensorData init_value = MQTT_COMPARISON__SENSOR_DATA__INIT;
  *message = init_value;
}
size_t mqtt_comparison__sensor_data__get_packed_size
                     (const MqttComparison__SensorData *message)
{
  assert(message->base.descriptor == &mqtt_comparison__sensor_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mqtt_comparison__sensor_data__pack
                     (const MqttComparison__SensorData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mqtt_comparison__sensor_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mqtt_comparison__sensor_data__pack_to_buffer
                     (const MqttComparison__SensorData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mqtt_comparison__sensor_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MqttComparison__SensorData *
       mqtt_comparison__sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MqttComparison__SensorData *)
     protobuf_c_message_unpack (&mqtt_comparison__sensor_data__descriptor,
                                allocator, len, data);
}
void   mqtt_comparison__sensor_data__free_unpacked
                     (MqttComparison__SensorData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mqtt_comparison__sensor_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mqtt_comparison__sensor_data__field_descriptors[5] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(MqttComparison__SensorData, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MqttComparison__SensorData, sensor_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(MqttComparison__SensorData, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(MqttComparison__SensorData, humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressure",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(MqttComparison__SensorData, pressure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mqtt_comparison__sensor_data__field_indices_by_name[] = {
  3,   /* field[3] = humidity */
  4,   /* field[4] = pressure */
  1,   /* field[1] = sensor_id */
  2,   /* field[2] = temperature */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange mqtt_comparison__sensor_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mqtt_comparison__sensor_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mqtt_comparison.SensorData",
  "SensorData",
  "MqttComparison__SensorData",
  "mqtt_comparison",
  sizeof(MqttComparison__SensorData),
  5,
  mqtt_comparison__sensor_data__field_descriptors,
  mqtt_comparison__sensor_data__field_indices_by_name,
  1,  mqtt_comparison__sensor_data__number_ranges,
  (ProtobufCMessageInit) mqtt_comparison__sensor_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
