/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sensor_data.proto */

#ifndef PROTOBUF_C_sensor_5fdata_2eproto__INCLUDED
#define PROTOBUF_C_sensor_5fdata_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct MqttComparison__SensorData MqttComparison__SensorData;


/* --- enums --- */


/* --- messages --- */

struct  MqttComparison__SensorData
{
  ProtobufCMessage base;
  double timestamp;
  char *sensor_id;
  double temperature;
  double humidity;
  double pressure;
};
#define MQTT_COMPARISON__SENSOR_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mqtt_comparison__sensor_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, 0, 0 }


/* MqttComparison__SensorData methods */
void   mqtt_comparison__sensor_data__init
                     (MqttComparison__SensorData         *message);
size_t mqtt_comparison__sensor_data__get_packed_size
                     (const MqttComparison__SensorData   *message);
size_t mqtt_comparison__sensor_data__pack
                     (const MqttComparison__SensorData   *message,
                      uint8_t             *out);
size_t mqtt_comparison__sensor_data__pack_to_buffer
                     (const MqttComparison__SensorData   *message,
                      ProtobufCBuffer     *buffer);
MqttComparison__SensorData *
       mqtt_comparison__sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mqtt_comparison__sensor_data__free_unpacked
                     (MqttComparison__SensorData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MqttComparison__SensorData_Closure)
                 (const MqttComparison__SensorData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mqtt_comparison__sensor_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sensor_5fdata_2eproto__INCLUDED */
